const template = [
  {
    position: { rowStart: 1, columnStart: 1, rowEnd: 3, columnEnd: 13 },
    inputFields: [
      {
        type: "text",
        position: { rowStart: 1, columnStart: 1, rowEnd: 3, columnEnd: 4 },
        label: "Character Name",
        value: "",
      },
      {
        type: "select",
        position: { rowStart: 1, columnStart: 4, rowEnd: 2, columnEnd: 6 },
        label: "Class",
        value: [],
        isMultiSelect: true,
        options: [
          "Barbarian",
          "Bard",
          "Cleric",
          "Druid",
          "Fighter",
          "Monk",
          "Paladin",
          "Ranger",
          "Rogue",
          "Sorcerer",
          "Warlock",
          "Wizard",
        ],
      },
      {
        type: "number",
        position: { rowStart: 0, columnStart: 0, rowEnd: 1, columnEnd: 12 },
        label: "Level",
        value: "",
      },
      {
        type: "select",
        position: { rowStart: 0, columnStart: 0, rowEnd: 1, columnEnd: 12 },
        label: "Race",
        value: "",
        options: [
          "Dwarf",
          "Elf",
          "Halfling",
          "Human",
          "Dragonborn",
          "Gnome",
          "Half-Elf",
          "Half-Orc",
          "Tiefling",
        ],
      },
      {
        type: "text",
        position: { rowStart: 0, columnStart: 0, rowEnd: 1, columnEnd: 12 },
        label: "Background",
        value: "",
      },
      {
        type: "text",
        position: { rowStart: 0, columnStart: 0, rowEnd: 1, columnEnd: 12 },
        label: "Alignment",
        value: "",
      },
      {
        type: "number",
        position: { rowStart: 0, columnStart: 0, rowEnd: 1, columnEnd: 12 },
        label: "Experience Points",
        value: "",
      },
      {
        type: "textarea",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Charater Notes",
        value: "",
      },
    ],
    title: "Character Info",
  },
  {
    position: { rowStart: 3, columnStart: 1, rowEnd: 9, columnEnd: 2 },
    inputFields: [
      {
        type: "numberWithModifier",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd:2 },
        label: "Strength",
        value: { main: 0, modifier: 0 },
      },
      {
        type: "numberWithModifier",
        position: { rowStart: 2, columnStart: 1, rowEnd: 3, columnEnd:2 },
        label: "Dexterity",
        value: { main: 0, modifier: 0 },
      },
      {
        type: "numberWithModifier",
        position: { rowStart: 3, columnStart: 1, rowEnd: 4, columnEnd:2 },
        label: "Constitution",
        value: { main: 0, modifier: 0 },
      },
      {
        type: "numberWithModifier",
        position: { rowStart: 4, columnStart: 1, rowEnd: 5, columnEnd:2 },
        label: "Intelligence",
        value: { main: 0, modifier: 0 },
      },
      {
        type: "numberWithModifier",
        position: { rowStart: 5, columnStart: 1, rowEnd: 6, columnEnd:2 },
        label: "Wisdom",
        value: { main: 0, modifier: 0 },
      },
      {
        type: "numberWithModifier",
        position: { rowStart: 6, columnStart: 1, rowEnd: 7, columnEnd:2 },
        label: "Charisma",
        value: { main: 0, modifier: 0 },
      },
    ],
    title: "Stats",
  },
  {
    position: { rowStart: 3, columnStart: 2, rowEnd: 9, columnEnd: 6 },
    inputFields: [
      {
        type: "checkbox",
        position: { rowStart: 0, columnStart: 0, rowEnd: 1, columnEnd: 12 },
        label: "Acrobatics",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Animal Handling",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Arcana",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Athletics",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Deception",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "History",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Insight",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Intimidation",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Investigation",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Medicine",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Nature",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Perception",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Performance",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Persuation",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Religion",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Sleight of Hand",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Stealth",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Survival",
        value: "",
        quantity: 1,
        isPrecisionRating: false,
        numberValue: 0,
      },
    ],
    title: "Skills",
  },
  {
    position: { rowStart: 3, columnStart: 6, rowEnd: 6, columnEnd: 10 },
    inputFields: [
      {
        type: "number",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Armor Class",
        value: "",
      },
      {
        type: "number",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Initiative",
        value: "",
      },
      {
        type: "number",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Speed",
        value: "",
      },
      {
        type: "number",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Current Hit Points",
        value: "",
      },
      {
        type: "number",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Temporary Hit Points",
        value: "",
      },
      {
        type: "text",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Hit Dice",
        value: "",
      },
      {
        type: "number",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Hit Dice Total",
        value: "",
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Death Save: Successes",
        value: "",
        quantity: 3,
        isPrecisionRating: false,
      },
      {
        type: "checkbox",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "Death Save: Failures",
        value: "",
        quantity: 3,
        isPrecisionRating: false,
      },
    ],
    title: "Combat",
  },
  {
    position: { rowStart: 6, columnStart: 6, rowEnd: 9, columnEnd: 10 },
    inputFields: [
      {
        type: "textarea",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "",
        value: "",
      },
    ],
    title: "Attacks & Spellcasting",
  },
  {
    position: { rowStart: 3, columnStart: 10, rowEnd: 12, columnEnd: 13 },
    inputFields: [
      {
        type: "textarea",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "",
        value: "",
      },
    ],
    title: "Features & Traits",
  },
  {
    position: { rowStart: 9, columnStart: 6, rowEnd: 12, columnEnd: 10 },
    inputFields: [
      {
        type: "textarea",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "",
        value: "",
      },
    ],
    title: "Equipment",
  },
  {
    position: { rowStart: 9, columnStart: 1, rowEnd: 12, columnEnd: 6 },
    inputFields: [
      {
        type: "textarea",
        position: { rowStart: 1, columnStart: 1, rowEnd: 2, columnEnd: 12 },
        label: "",
        value: "",
      },
    ],
    title: "Other Proficiencies & Languages",
  },
]

export default template
